default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("PGHOST", "db") %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  database: <%= ENV.fetch("PGDATABASE", "thehouseguy_dev") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_TEST", "thehouseguy_test") %>

staging:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_STAGING", "thehouseguy_staging") %>

production:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE_PRODUCTION", "thehouseguy_production") %>
