# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  rets_login_url: 'https://pt.rets.crmls.org/contact/rets/login'
  rets_username: 'THEHOUSEGUY'
  rets_password: 'nYR!cH3x'
  rets_version: 'RETS/1.8'  

# Environmental secrets are only available for that specific environment.
development:
  secret_key_base: 30b9c87502e54d382caab32507880fbecc7b00259abb2cf32df2a6f0cf50414d40b7a4161fd41dc4707f52b07143ca165d21fa5be1ca372d8cf20560fdfdd6b7

staging:
  secret_key_base: 71b43fe2352a5b8c25862d180cd9b21258bbf6ce1da06141cb6e43c2f02c3df917a21c98b6301f75d0a6e58b6d7524b5ca3b8f6f6b466b28fa9cbf1c3dd28a15

test:
  secret_key_base: 71b43fe2352a5b8c25862d180cd9b21258bbf6ce1da06141cb6e43c2f02c3df917a21c98b6301f75d0a6e58b6d7524b5ca3b8f6f6b466b28fa9cbf1c3dd28a15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>